<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Book;
use Illuminate\Support\Str;

class BooksSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $books = [
            [
                'title' => 'A Game of Thrones',
                'author' => 'George R. R. Martin',
                'publisher' => 'Bantam Books',
                'genre' => 'Fantasy',
                'pages' => 694,
                'year' => 1996,
                'isbn' => '9780553103540',
                'rating' => 4.5,
                'status' => 'available',
                'slug' => Str::slug('A Game of Thrones'),
                'description' => 'In the Seven Kingdoms of Westeros, where summers span decades and winters can last a lifetime, trouble is brewing. The coldness is returning from the frozen wastelands to the north, and ancient evils are awakening. Meanwhile, conspiracy and betrayal play out across the continent among the nobles and royals who covet the Iron Throne.',
                'cover_url' => 'https://placehold.co/400x600/1a1a2e/eee?text=A+Game+of+Thrones&font=roboto',
                'notes' => 'First book in the epic A Song of Ice and Fire series. Complex characters and intricate plot lines.',
                'review' => 'A masterpiece of fantasy literature. Martin creates a richly detailed world with morally complex characters. The political intrigue rivals the best historical fiction, while the fantasy elements add depth and mystery. Highly recommended for fans of epic fantasy.',
            ],
            [
                'title' => 'Harry Potter and the Philosopher\'s Stone',
                'author' => 'J.K. Rowling',
                'publisher' => 'Bloomsbury',
                'genre' => 'Fantasy',
                'pages' => 223,
                'year' => 1997,
                'isbn' => '9780747532699',
                'rating' => 4.7,
                'status' => 'available',
                'slug' => Str::slug('Harry Potter and the Philosopher\'s Stone'),
                'description' => 'Harry Potter has never been the star of a Quidditch team, scoring points while riding a broom far above the ground. He knows no spells, has never helped to hatch a dragon, and has never worn a cloak of invisibility. All he knows is a miserable life with the Dursleys. But all that is about to change when a mysterious letter arrives by owl messenger.',
                'cover_url' => 'https://placehold.co/400x600/7f2982/eee?text=Harry+Potter+1&font=roboto',
                'notes' => 'The book that started the magical phenomenon. Perfect for all ages.',
                'review' => 'An enchanting introduction to the wizarding world. Rowling\'s imagination knows no bounds, creating a magical universe that feels real and lived-in. The perfect blend of adventure, friendship, and magic. A must-read for everyone.',
            ],
            [
                'title' => 'Demon Slayer: Kimetsu no Yaiba, Vol. 1',
                'author' => 'Koyoharu Gotouge',
                'publisher' => 'VIZ Media',
                'genre' => 'Manga/Action',
                'pages' => 192,
                'year' => 2018,
                'isbn' => '9781974700523',
                'rating' => 4.6,
                'status' => 'available',
                'slug' => Str::slug('Demon Slayer Kimetsu no Yaiba Vol 1'),
                'description' => 'Tanjiro sets out on the path of the Demon Slayer to save his sister and avenge his family! In Taisho-era Japan, Tanjiro Kamado is a kindhearted boy who makes a living selling charcoal. But his peaceful life is shattered when a demon slaughters his entire family. His little sister Nezuko is the only survivor, but she has been transformed into a demon herself!',
                'cover_url' => 'https://placehold.co/400x600/c03221/eee?text=Demon+Slayer+Vol+1&font=roboto',
                'notes' => 'Beautiful artwork and compelling story. First volume of the series.',
                'review' => 'An outstanding manga with breathtaking artwork. The story is emotionally gripping, following Tanjiro\'s journey to save his demon-transformed sister. The action sequences are dynamic and the character development is exceptional. Highly recommended for manga fans.',
            ],
            [
                'title' => 'Spider-Man: Birth of Venom',
                'author' => 'Various',
                'publisher' => 'Marvel Comics',
                'genre' => 'Comics/Superhero',
                'pages' => 328,
                'year' => 2007,
                'isbn' => '9780785124986',
                'rating' => 4.4,
                'status' => 'available',
                'slug' => Str::slug('Spider-Man Birth of Venom'),
                'description' => 'Collects Amazing Spider-Man #298-300, #315-317, #332-333, #346-347; Web of Spider-Man #1; Avengers: Deathtrap, The Vault; and Dardevil #279 (partial). The story that transformed comics! Peter Parker\'s life is turned upside down when he learns the true nature of his black costume.',
                'cover_url' => 'https://placehold.co/400x600/000000/eee?text=Spider-Man+Venom&font=roboto',
                'notes' => 'Classic storyline introducing one of Spider-Man\'s most iconic villains.',
                'review' => 'A must-read for any Spider-Man fan. This collection showcases the birth of one of Marvel\'s most complex villains. The psychological thriller aspects mixed with superhero action make it a standout. The artwork is classic and the story remains relevant.',
            ],
            [
                'title' => 'The Avengers: The Kree-Skrull War',
                'author' => 'Roy Thomas & Neal Adams',
                'publisher' => 'Marvel Comics',
                'genre' => 'Comics/Superhero',
                'pages' => 280,
                'year' => 2000,
                'isbn' => '9780785107996',
                'rating' => 4.3,
                'status' => 'available',
                'slug' => Str::slug('The Avengers The Kree-Skrull War'),
                'description' => 'Collects Avengers #89-97. Earth has become the battleground for the greatest war the galaxy has ever seen - the legendary Kree-Skrull War! Captain Marvel, the Kree warrior, must choose between his people and his adopted home, while the Avengers are caught in the middle!',
                'cover_url' => 'https://placehold.co/400x600/ed1c24/eee?text=Avengers+Kree-Skrull&font=roboto',
                'notes' => 'Epic cosmic storyline that defined modern Marvel Comics.',
                'review' => 'A groundbreaking storyline that set the template for cosmic Marvel stories. The scope is massive, the stakes are high, and the art by Neal Adams is legendary. Essential reading for understanding Marvel\'s cosmic universe.',
            ],
            [
                'title' => 'Harry Potter and the Chamber of Secrets',
                'author' => 'J.K. Rowling',
                'publisher' => 'Bloomsbury',
                'genre' => 'Fantasy',
                'pages' => 251,
                'year' => 1998,
                'isbn' => '9780747538493',
                'rating' => 4.6,
                'status' => 'available',
                'slug' => Str::slug('Harry Potter and the Chamber of Secrets'),
                'description' => 'Ever since Harry Potter had come home for the summer, the Dursleys had been so mean and hideous that all Harry wanted was to get back to the Hogwarts School for Witchcraft and Wizardry. But just as he\'s packing his bags, Harry receives a warning from a strange impish creature who says that if Harry returns to Hogwarts, disaster will strike.',
                'cover_url' => 'https://placehold.co/400x600/7f2982/eee?text=Harry+Potter+2&font=roboto',
                'notes' => 'Second book in the Harry Potter series. Introduces the Chamber of Secrets mystery.',
                'review' => 'The second installment builds wonderfully on the first book. The mystery is engaging, the stakes feel higher, and we learn more about the wizarding world. Rowling\'s world-building continues to impress.',
            ],
            [
                'title' => 'A Clash of Kings',
                'author' => 'George R. R. Martin',
                'publisher' => 'Bantam Books',
                'genre' => 'Fantasy',
                'pages' => 768,
                'year' => 1999,
                'isbn' => '9780553108033',
                'rating' => 4.4,
                'status' => 'available',
                'slug' => Str::slug('A Clash of Kings'),
                'description' => 'A comet the color of blood and flame cuts across the sky. And from the ancient citadel of Dragonstone to the forbidding shores of Winterfell, chaos reigns. Six factions struggle for control of a divided land and the Iron Throne of the Seven Kingdoms.',
                'cover_url' => 'https://placehold.co/400x600/1a1a2e/eee?text=A+Clash+of+Kings&font=roboto',
                'notes' => 'Second book in A Song of Ice and Fire. Multiple storylines converge.',
                'review' => 'Martin expands his already vast world even further. The political intrigue deepens, new characters are introduced, and the plot becomes even more complex. A worthy sequel that raises the stakes.',
            ],
            [
                'title' => 'Demon Slayer: Kimetsu no Yaiba, Vol. 2',
                'author' => 'Koyoharu Gotouge',
                'publisher' => 'VIZ Media',
                'genre' => 'Manga/Action',
                'pages' => 192,
                'year' => 2018,
                'isbn' => '9781974700530',
                'rating' => 4.7,
                'status' => 'available',
                'slug' => Str::slug('Demon Slayer Kimetsu no Yaiba Vol 2'),
                'description' => 'Tanjiro and Nezuko cross paths with two powerful demons who fight with magical weapons. Even help from Tamayo and Yushiro may not be enough to defeat these demons who claim to belong to the Twelve Kizuki that directly serve Kibutsuji, the demon responsible for all of Tanjiro\'s woes!',
                'cover_url' => 'https://placehold.co/400x600/c03221/eee?text=Demon+Slayer+Vol+2&font=roboto',
                'notes' => 'Continues Tanjiro\'s journey. Introduces more powerful demons.',
                'review' => 'The series continues to impress with stunning visuals and emotional depth. The fight scenes are spectacular and the character development remains strong. Can\'t wait to read more!',
            ],
            [
                'title' => 'Demon Slayer: Kimetsu no Yaiba, Vol. 3',
                'author' => 'Koyoharu Gotouge',
                'publisher' => 'VIZ Media',
                'genre' => 'Manga/Action',
                'pages' => 192,
                'year' => 2018,
                'isbn' => '9781974700547',
                'rating' => 4.8,
                'status' => 'available',
                'slug' => Str::slug('Demon Slayer Kimetsu no Yaiba Vol 3'),
                'description' => 'Tanjiro sets out on the path of the Demon Slayer to save his sister and avenge his family! Tanjiro and Nezuko face off against a powerful demon who has been terrorizing a village. With the help of Nezuko and his own growing skills, Tanjiro must defeat this demon before more innocent people are killed.',
                'cover_url' => 'https://placehold.co/400x600/c03221/eee?text=Demon+Slayer+Vol+3&font=roboto',
                'notes' => 'Volume 3 continues the intense action and character development.',
                'review' => 'The story keeps getting better! The bond between Tanjiro and Nezuko is heartwarming, and the fight choreography in manga form is incredible.',
            ],
            [
                'title' => 'Demon Slayer: Kimetsu no Yaiba, Vol. 4',
                'author' => 'Koyoharu Gotouge',
                'publisher' => 'VIZ Media',
                'genre' => 'Manga/Action',
                'pages' => 192,
                'year' => 2018,
                'isbn' => '9781974702121',
                'rating' => 4.7,
                'status' => 'available',
                'slug' => Str::slug('Demon Slayer Kimetsu no Yaiba Vol 4'),
                'description' => 'Tanjiro, Zenitsu and Inosuke battle a terrible guardian of the Tsuzumi Mansion. The demon uses a Blood Demon Art to control and turn the house into a maze, trapping them inside. Can they escape alive?',
                'cover_url' => 'https://placehold.co/400x600/c03221/eee?text=Demon+Slayer+Vol+4&font=roboto',
                'notes' => 'Introduction of fan-favorite characters Zenitsu and Inosuke.',
                'review' => 'This volume introduces two amazing characters that add humor and depth to the story. The Tsuzumi Mansion arc is thrilling!',
            ],
            [
                'title' => 'Demon Slayer: Kimetsu no Yaiba, Vol. 5',
                'author' => 'Koyoharu Gotouge',
                'publisher' => 'VIZ Media',
                'genre' => 'Manga/Action',
                'pages' => 192,
                'year' => 2019,
                'isbn' => '9781974702138',
                'rating' => 4.8,
                'status' => 'available',
                'slug' => Str::slug('Demon Slayer Kimetsu no Yaiba Vol 5'),
                'description' => 'Despite some comic misunderstandings that almost blow their cover, Tanjiro, Inosuke and Zenitsu smoke out Daki, a demon that has been devouring the residents of an entertainment district for years. The Hashira Tengen Uzui and his ninja companions engage Daki, but if they cannot handle her, what chance do Tanjiro and his friends have of taking on one of Kibutsuji\'s Twelve Kizuki?',
                'cover_url' => 'https://placehold.co/400x600/c03221/eee?text=Demon+Slayer+Vol+5&font=roboto',
                'notes' => 'Features the intense battle against Daki.',
                'review' => 'An explosive volume! The action reaches new heights and the stakes have never been higher. Absolutely riveting!',
            ],
            [
                'title' => 'Demon Slayer: Kimetsu no Yaiba, Vol. 6',
                'author' => 'Koyoharu Gotouge',
                'publisher' => 'VIZ Media',
                'genre' => 'Manga/Action',
                'pages' => 192,
                'year' => 2019,
                'isbn' => '9781974704415',
                'rating' => 4.9,
                'status' => 'available',
                'slug' => Str::slug('Demon Slayer Kimetsu no Yaiba Vol 6'),
                'description' => 'Tanjiro and his companions are in for a surprise when they encounter the Spider Family on Mt. Natagumo. They must face a demon whose threads can control both humans and demons like puppets. Can they save themselves and their friends from this deadly trap?',
                'cover_url' => 'https://placehold.co/400x600/c03221/eee?text=Demon+Slayer+Vol+6&font=roboto',
                'notes' => 'The Spider Family arc begins - one of the most intense arcs.',
                'review' => 'Nightmare fuel! The Spider Family is terrifying. This volume showcases Gotouge\'s ability to create truly frightening demons. A must-read!',
            ],
            [
                'title' => 'Batman: The Killing Joke',
                'author' => 'Alan Moore',
                'publisher' => 'DC Comics',
                'genre' => 'Comics/Superhero',
                'pages' => 64,
                'year' => 1988,
                'isbn' => '9781401216672',
                'rating' => 4.8,
                'status' => 'available',
                'slug' => Str::slug('Batman The Killing Joke'),
                'description' => 'Presented for the first time with stark, stunning new coloring by Brian Bolland, BATMAN: THE KILLING JOKE is Alan Moore\'s unforgettable meditation on the razor-thin line between sanity and insanity, heroism and villainy, comedy and tragedy.',
                'cover_url' => 'https://placehold.co/400x600/1a1a2e/yellow?text=Batman+Killing+Joke&font=roboto',
                'notes' => 'One of the greatest Batman stories ever told. Dark and psychological.',
                'review' => 'A masterpiece. Alan Moore and Brian Bolland create a haunting exploration of the Joker\'s origin. This story redefined the Batman-Joker dynamic forever. Essential reading for any comic fan.',
            ],
            [
                'title' => 'Batman: Year One',
                'author' => 'Frank Miller',
                'publisher' => 'DC Comics',
                'genre' => 'Comics/Superhero',
                'pages' => 144,
                'year' => 1988,
                'isbn' => '9781401207526',
                'rating' => 4.7,
                'status' => 'available',
                'slug' => Str::slug('Batman Year One'),
                'description' => 'In 1986, Frank Miller and David Mazzucchelli produced this groundbreaking reinterpretation of the origin of Batman. Sometimes careless and naive, this Dark Knight is far from the flawless vigilante he is today. Miller\'s gripping realism changed the face of comics forever.',
                'cover_url' => 'https://placehold.co/400x600/1a1a2e/yellow?text=Batman+Year+One&font=roboto',
                'notes' => 'The definitive Batman origin story.',
                'review' => 'Frank Miller strips Batman down to his core and rebuilds him from the ground up. A gritty, realistic take that influenced all Batman media that followed. Brilliant storytelling.',
            ],
            [
                'title' => 'The Dark Knight Returns',
                'author' => 'Frank Miller',
                'publisher' => 'DC Comics',
                'genre' => 'Comics/Superhero',
                'pages' => 224,
                'year' => 1986,
                'isbn' => '9781563893421',
                'rating' => 4.9,
                'status' => 'available',
                'slug' => Str::slug('The Dark Knight Returns'),
                'description' => 'It is ten years after an aging Batman has retired and Gotham City has sunk deeper into decadence and lawlessness. Now as his city needs him most, the Dark Knight returns in a blaze of glory.',
                'cover_url' => 'https://placehold.co/400x600/1a1a2e/yellow?text=Dark+Knight+Returns&font=roboto',
                'notes' => 'Revolutionary graphic novel that redefined superhero comics.',
                'review' => 'A landmark achievement in comic book history. Miller\'s vision of an older, grizzled Batman is both powerful and poignant. This book proved that superhero comics could be sophisticated literature.',
            ],
            [
                'title' => 'Watchmen',
                'author' => 'Alan Moore',
                'publisher' => 'DC Comics',
                'genre' => 'Comics/Superhero',
                'pages' => 416,
                'year' => 1987,
                'isbn' => '9781401245252',
                'rating' => 5.0,
                'status' => 'available',
                'slug' => Str::slug('Watchmen'),
                'description' => 'A complex, multi-layered mystery and one of the most influential stories of all time, WATCHMEN is set in an alternate 1985 America in which costumed superheroes are part of the fabric of everyday society, and the "Doomsday Clock" - which charts the USA\'s tension with the Soviet Union - is permanently set at five minutes to midnight.',
                'cover_url' => 'https://placehold.co/400x600/1a1a2e/yellow?text=Watchmen&font=roboto',
                'notes' => 'Considered one of the greatest graphic novels ever written.',
                'review' => 'A masterwork that transcends the medium. Moore deconstructs the superhero genre while telling a gripping mystery. Every panel is packed with detail and meaning. Essential reading.',
            ],
            [
                'title' => 'The Amazing Spider-Man: Kraven\'s Last Hunt',
                'author' => 'J.M. DeMatteis',
                'publisher' => 'Marvel Comics',
                'genre' => 'Comics/Superhero',
                'pages' => 160,
                'year' => 1987,
                'isbn' => '9780785134503',
                'rating' => 4.6,
                'status' => 'available',
                'slug' => Str::slug('The Amazing Spider-Man Kravens Last Hunt'),
                'description' => 'Kraven the Hunter has stalked and killed every animal known to man. But there is one beast that has eluded him. One quarry that has mocked him at every turn: the wall-crawling web-slinger known as Spider-Man. And to prove that he is the hero\'s master, he will pull on his costume and become him!',
                'cover_url' => 'https://placehold.co/400x600/ed1c24/eee?text=Kravens+Last+Hunt&font=roboto',
                'notes' => 'Dark and psychological Spider-Man story.',
                'review' => 'A haunting, psychological thriller that explores themes of identity and obsession. DeMatteis crafts a story that\'s as much about Kraven as it is about Spider-Man. Unforgettable.',
            ],
            [
                'title' => 'X-Men: Days of Future Past',
                'author' => 'Chris Claremont',
                'publisher' => 'Marvel Comics',
                'genre' => 'Comics/Superhero',
                'pages' => 144,
                'year' => 1981,
                'isbn' => '9780785164531',
                'rating' => 4.5,
                'status' => 'available',
                'slug' => Str::slug('X-Men Days of Future Past'),
                'description' => 'Relive the legendary first journey into the dystopian future of 2013 - where Sentinels stalk the Earth, and the X-Men are humanity\'s only hope...until they die! Also featuring the first appearance of Alpha Flight, the return of the Wendigo, the history of the X-Men from Cyclops himself...and a demon for Christmas!?',
                'cover_url' => 'https://placehold.co/400x600/ed1c24/eee?text=X-Men+Days+Future+Past&font=roboto',
                'notes' => 'Classic X-Men storyline that defined the franchise.',
                'review' => 'One of the most influential X-Men stories ever told. The dystopian future concept has been revisited countless times, but the original remains the best. Claremont at his finest.',
            ],
            [
                'title' => 'Infinity Gauntlet',
                'author' => 'Jim Starlin',
                'publisher' => 'Marvel Comics',
                'genre' => 'Comics/Superhero',
                'pages' => 256,
                'year' => 1991,
                'isbn' => '9780785156598',
                'rating' => 4.8,
                'status' => 'available',
                'slug' => Str::slug('Infinity Gauntlet'),
                'description' => 'The Mad Titan Thanos has seized control of Infinity Gauntlet and with it near-omnipotent power! Who can stop this deadly new overlord? All of Marvel\'s top heroes star in this epic of cosmic proportions!',
                'cover_url' => 'https://placehold.co/400x600/ed1c24/eee?text=Infinity+Gauntlet&font=roboto',
                'notes' => 'Epic cosmic event that inspired the MCU Infinity War movies.',
                'review' => 'The ultimate Marvel event. Thanos is at his most powerful and threatening. The scope is cosmic, the stakes are universal, and every hero must unite. A must-read Marvel classic.',
            ],
            [
                'title' => 'Civil War',
                'author' => 'Mark Millar',
                'publisher' => 'Marvel Comics',
                'genre' => 'Comics/Superhero',
                'pages' => 208,
                'year' => 2007,
                'isbn' => '9780785125358',
                'rating' => 4.4,
                'status' => 'available',
                'slug' => Str::slug('Civil War'),
                'description' => 'The landscape of the Marvel Universe is changing, and it\'s time to choose: Whose side are you on? A conflict has been brewing from which no one will emerge unscathed. When a tragic battle blows a hole in the city of Stamford, killing hundreds of people, the U.S. government demands that all super heroes unmask and register their powers.',
                'cover_url' => 'https://placehold.co/400x600/ed1c24/eee?text=Civil+War&font=roboto',
                'notes' => 'Major Marvel event that divided heroes and fans alike.',
                'review' => 'A thought-provoking story that asks difficult questions about freedom and responsibility. The hero vs hero conflict is handled brilliantly, making both sides sympathetic. Influential and engaging.',
            ],
        ];

        foreach ($books as $book) {
            Book::create($book);
        }
    }
}
